import asyncio

from grpclib.client import Channel

# generated by protoc
from helloworld_pb2 import Request
from helloworld_grpc import ServiceStub


async def main() -> None:
    async with Channel('127.0.0.1', 8080) as channel:
        greeter = ServiceStub(channel)

        reply = await greeter.SayHello(Request(name='Dr. Strange'))
        print(reply.message)


if __name__ == '__main__':
    asyncio.run(main())